name: NLU Documentation Pipeline

on:
  push:
    branches: [main]
    paths:
      - '**.md'
      - '**.py'
      - '**.yaml'
      - '**.yml'
      - 'src/**'
      - 'tests/**'
      - 'docs/**'
      - 'prompt-library/**'
      - 'modules/**'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  process-documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml numpy networkx matplotlib

      - name: Run document processor
        run: |
          python tools/nlu/processor.py --base-path . --output-dir docs/nlu

      - name: Generate embeddings
        run: |
          python tools/nlu/embedder.py --registry docs/nlu/document_registry.json --output docs/nlu/embeddings/document_embeddings.json

      - name: Generate synthesis reports
        run: |
          python tools/nlu/synthesizer.py --registry docs/nlu/document_registry.json --relationships docs/nlu/relationship_map.json --output-dir docs/synthesis/reports

      - name: Check documentation coverage
        run: |
          python tools/nlu/validator.py --registry docs/nlu/document_registry.json --criteria docs/nlu/schemas/completeness_criteria.yaml --report docs/synthesis/reports/validation_report.md

      - name: Commit updated documentation
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/nlu docs/synthesis
          git commit -m "[docs] Update NLU documentation analysis" || echo "No changes to commit"
          git push